exports.getHall = function(startID) {
	return [{
		id: startID,
		tag: 'floorHall'
	}, {
		id: startID+1,
		tag: 'wallHall1'
	}, {
		id: startID+2,
		tag: 'wallHall2'
	}, {
		id: startID+3,
		tag: 'wallHall3'
	}];
};

exports.getRestaurant = function(startID) {
	return [{
		id: startID,
		tag: 'floorRestaurant'
	}, {
		id: startID+1,
		tag: 'floorKitchen'
	}, {
		id: startID+2,
		tag: 'wallRestaurant1'
	}, {
		id: startID+3,
		tag: 'wallRestaurant2'
	}, {
		id: startID+4,
		tag: 'wallRestaurant3'
	}, {
		id: startID+5,
		tag: 'wallRestaurant4'
	}, {
		id: startID+6,
		tag: 'wallRestaurant5'
	}, {
		id: startID+7,
		tag: 'wallRestaurant6'
	}, {
		id: startID+8,
		tag: 'wallRestaurant7'
	}, {
		id: startID+9,
		tag: 'wallRestaurant8'
	}, {
		id: startID+10,
		tag: 'wallKitchen1'
	}, {
		id: startID+11,
		tag: 'wallKitchen2'
	}, {
		id: startID+12,
		tag: 'wallKitchen3'
	}, {
		id: startID+13,
		tag: 'tableRestaurant1'
	}, {
		id: startID+14,
		tag: 'tableRestaurant2'
	}, {
		id: startID+15,
		tag: 'tableRestaurant3'
	}, {
		id: startID+16,
		tag: 'tableRestaurant4'
	}, {
		id: startID+17,
		tag: 'tableRestaurant5'
	}, {
		id: startID+18,
		tag: 'tableRestaurant6'
	}, {
		id: startID+19,
		tag: 'tableRestaurant7'
	}, {
		id: startID+20,
		tag: 'counterbar'
	}, {
		id: startID+21,
		tag: 'tableRestaurant9'
	}, {
		id: startID+22,
		tag: 'tableRestaurant10'
	}, {
		id: startID+23,
		tag: 'tableRestaurant11'
	}, {
		id: startID+24,
		tag: 'tableRestaurant12'
	}, {
		id: startID+25,
		tag: 'tableRestaurant13'
	}, {
		id: startID+26,
		tag: 'tableRestaurant14'
	}, {
		id: startID+27,
		tag: 'windowRestaurant1'
	}, {
		id: startID+28,
		tag: 'windowRestaurant2'
	}, {
		id: startID+29,
		tag: 'windowRestaurant3'
	}, {
		id: startID+30,
		tag: 'windowRestaurant4'
	}, {
		id: startID+31,
		tag: 'lightRestaurant1'
	}, {
		id: startID+32,
		tag: 'lightRestaurant2'
	}, {
		id: startID+33,
		tag: 'lightRestaurant3'
	}, {
		id: startID+34,
		tag: 'lightRestaurant4'
	}, {
		id: startID+35,
		tag: 'lightRestaurant5'
	}, {
		id: startID+36,
		tag: 'lightKitchen1'
	}, {
		id: startID+37,
		tag: 'lightKitchen2'
	}, {
		id: startID+38,
		tag: 'washbasin'
	}, {
		id: startID+39,
		tag: 'countertop1'
	}, {
		id: startID+40,
		tag: 'countertop2'
	}, {
		id: startID+41,
		tag: 'countertop3'
	}, {
		id: startID+42,
		tag: 'stove1'
	}, {
		id: startID+43,
		tag: 'stove2'
	}, {
		id: startID+44,
		tag: 'stove3'
	}, {
		id: startID+45,
		tag: 'frige1'
	}, {
		id: startID+46,
		tag: 'frige2'
	}, {
		id: startID+47,
		tag: 'frige3'
	}, {
		id: startID+48,
		tag: 'rack1'
	}, {
		id: startID+49,
		tag: 'rack2'
	}, {
		id: startID+50,
		tag: 'rack3'
	}, {
		id: startID+51,
		tag: 'tableKitchen'
	}, {
		id: startID+52,
		tag: 'doorKitchen'
	}, {
		id: startID+53,
		tag: 'doorRestaurant'
	}
	];
};

exports.getRooms = function(startID) {
	return [{
		id: startID,
		tag: 'floorRoomsPart1'
	}, {
		id: startID+1,
		tag: 'floorRoomsPart2'
	}, {
		id: startID+2,
		tag: 'floorRoomsPart3'
	}, {
		id: startID+3,
		tag: 'floorRoomsPart4'
	}, {
		id: startID+4,
		tag: 'wallRooms1'
	}, {
		id: startID+5,
		tag: 'wallRooms2'
	}, {
		id: startID+6,
		tag: 'wallRooms3'
	}, {
		id: startID+7,
		tag: 'wallRooms4'
	}, {
		id: startID+8,
		tag: 'wallRooms5'
	}, {
		id: startID+9,
		tag: 'wallRooms6'
	}, {
		id: startID+10,
		tag: 'wallRooms7'
	}, {
		id: startID+11,
		tag: 'wallRooms8'
	}, {
		id: startID+12,
		tag: 'wallRooms9'
	}, {
		id: startID+13,
		tag: 'wallRooms10'
	}, {
		id: startID+14,
		tag: 'wallRooms11'
	}, {
		id: startID+15,
		tag: 'wallRooms12'
	}, {
		id: startID+16,
		tag: 'wallRooms13'
	}, {
		id: startID+17,
		tag: 'wallRooms14'
	}, {
		id: startID+18,
		tag: 'wallRooms15'
	}, {
		id: startID+19,
		tag: 'wallRooms16'
	}, {
		id: startID+20,
		tag: 'wallRooms17'
	}, {
		id: startID+21,
		tag: 'wallRooms18'
	}, {
		id: startID+22,
		tag: 'wallRooms19'
	}, {
		id: startID+23,
		tag: 'wallRooms20'
	}, {
		id: startID+24,
		tag: 'wallRooms21'
	}, {
		id: startID+25,
		tag: 'wallRooms22'
	}, {
		id: startID+26,
		tag: 'wallRooms23'
	}, {
		id: startID+27,
		tag: 'wallRooms24'
	}, {
		id: startID+28,
		tag: 'wallRooms25'
	}, {
		id: startID+29,
		tag: 'wallRooms26'
	}, {
		id: startID+30,
		tag: 'wallRooms27'
	}, {
		id: startID+31,
		tag: 'wallRooms28'
	}, {
		id: startID+32,
		tag: 'wallRooms29'
	}, {
		id: startID+33,
		tag: 'wallRooms30'
	}, {
		id: startID+34,
		tag: 'wallRooms31'
	}, {
		id: startID+35,
		tag: 'wallRooms32'
	}, {
		id: startID+36,
		tag: 'wallRooms33'
	}, {
		id: startID+37,
		tag: 'wallRooms34'
	}, {
		id: startID+38,
		tag: 'wallRooms35'
	}, {
		id: startID+39,
		tag: 'wallRooms36'
	}, {
		id: startID+40,
		tag: 'wallRooms37'
	}, {
		id: startID+41,
		tag: 'wallRooms38'
	}, {
		id: startID+42,
		tag: 'wallRooms39'
	}, {
		id: startID+43,
		tag: 'wallRooms40'
	}, {
		id: startID+44,
		tag: 'wallRooms41'
	}, {
		id: startID+45,
		tag: 'wallRooms42'
	}, {
		id: startID+46,
		tag: 'wallRooms43'
	}, {
		id: startID+47,
		tag: 'wallRooms44'
	}, {
		id: startID+48,
		tag: 'wallRooms45'
	}, {
		id: startID+49,
		tag: 'wallRooms46'
	}, {
		id: startID+50,
		tag: 'wallRooms47'
	}, {
		id: startID+51,//this start
		tag: 'wallRooms48'
	}, {
		id: startID+52,
		tag: 'wallRooms49'
	}, {
		id: startID+53,
		tag: 'wallRooms50'
	}, {
		id: startID+54,
		tag: 'wallRooms51'
	}, {
		id: startID+55,
		tag: 'wallRooms52'
	}, {
		id: startID+56,
		tag: 'wallRooms53'
	}, {
		id: startID+57,
		tag: 'wallRooms54'
	}, {
		id: startID+58,
		tag: 'wallRooms55'
	}, {
		id: startID+59,
		tag: 'wallRooms56'
	}, {
		id: startID+60,
		tag: 'wallRooms57'
	}, {
		id: startID+61,
		tag: 'wallRooms58'
	}, {
		id: startID+62,
		tag: 'wallRooms59'
	}, {
		id: startID+63,
		tag: 'wallRooms60'
	}, {
		id: startID+64,
		tag: 'wallRooms61'
	}, {
		id: startID+65,
		tag: 'wallRooms62'
	}, {
		id: startID+67,
		tag: 'wallRooms63'
	}, {
		id: startID+68,
		tag: 'wallRooms64'
	}, {
		id: startID+69,
		tag: 'wallRooms65'
	}];
};

exports.getSecurity = function(startID) {
	return [{
		id: startID,
		tag: 'floorSecurity'
	}, {
		id: startID+1,
		tag: 'wallSecurity1'
	}, {
		id: startID+2,
		tag: 'wallSecurity2'
	}, {
		id: startID+3,
		tag: 'wallSecurity3'
	}, {
		id: startID+4,
		tag: 'wallSecurity4'
	}, {
		id: startID+5,
		tag: 'wallSecurity5'
	}];
};
