exports.getHall = function(startID) {
	return [{
		id: startID,
		tag: 'floorHall'
	}, {
		id: startID+1,
		tag: 'wallHall1'
	}, {
		id: startID+2,
		tag: 'wallHall2'
	}, {
		id: startID+3,
		tag: 'wallHall3'
	}, {
		id: startID+4,
		tag: 'reception'
	}, {
		id: startID+5,
		tag: 'doorMain'
	}, {
		id: startID+6,
		tag: 'windowHall1'
	}, {
		id: startID+7,
		tag: 'windowHall2'
	}, {
		id: startID+8,
		tag: 'windowHall3'
	}, {
		id: startID+9,
		tag: 'grass'
	}
	];
};

exports.getRestaurant = function(startID) {
	return [{
		id: startID,
		tag: 'floorRestaurant'
	}, {
		id: startID+1,
		tag: 'floorKitchen'
	}, {
		id: startID+2,
		tag: 'wallRestaurant1'
	}, {
		id: startID+3,
		tag: 'wallRestaurant2'
	}, {
		id: startID+4,
		tag: 'wallRestaurant3'
	}, {
		id: startID+5,
		tag: 'wallRestaurant4'
	}, {
		id: startID+6,
		tag: 'wallRestaurant5'
	}, {
		id: startID+7,
		tag: 'wallRestaurant6'
	}, {
		id: startID+8,
		tag: 'wallRestaurant7'
	}, {
		id: startID+9,
		tag: 'wallRestaurant8'
	}, {
		id: startID+10,
		tag: 'wallKitchen1'
	}, {
		id: startID+11,
		tag: 'wallKitchen2'
	}, {
		id: startID+12,
		tag: 'wallKitchen3'
	}, {
		id: startID+13,
		tag: 'tableRestaurant1'
	}, {
		id: startID+14,
		tag: 'tableRestaurant2'
	}, {
		id: startID+15,
		tag: 'tableRestaurant3'
	}, {
		id: startID+16,
		tag: 'tableRestaurant4'
	}, {
		id: startID+17,
		tag: 'tableRestaurant5'
	}, {
		id: startID+18,
		tag: 'tableRestaurant6'
	}, {
		id: startID+19,
		tag: 'tableRestaurant7'
	}, {
		id: startID+20,
		tag: 'counterbar'
	}, {
		id: startID+21,
		tag: 'tableRestaurant9'
	}, {
		id: startID+22,
		tag: 'tableRestaurant10'
	}, {
		id: startID+23,
		tag: 'tableRestaurant11'
	}, {
		id: startID+24,
		tag: 'tableRestaurant12'
	}, {
		id: startID+25,
		tag: 'tableRestaurant13'
	}, {
		id: startID+26,
		tag: 'tableRestaurant14'
	}, {
		id: startID+27,
		tag: 'windowRestaurant1'
	}, {
		id: startID+28,
		tag: 'windowRestaurant2'
	}, {
		id: startID+29,
		tag: 'windowRestaurant3'
	}, {
		id: startID+30,
		tag: 'windowRestaurant4'
	}, {
		id: startID+31,
		tag: 'washbasin'
	}, {
		id: startID+32,
		tag: 'countertop1'
	}, {
		id: startID+33,
		tag: 'countertop2'
	}, {
		id: startID+34,
		tag: 'countertop3'
	}, {
		id: startID+35,
		tag: 'stove1'
	}, {
		id: startID+36,
		tag: 'stove2'
	}, {
		id: startID+37,
		tag: 'stove3'
	}, {
		id: startID+38,
		tag: 'frige1'
	}, {
		id: startID+39,
		tag: 'frige2'
	}, {
		id: startID+40,
		tag: 'frige3'
	}, {
		id: startID+41,
		tag: 'rack1'
	}, {
		id: startID+42,
		tag: 'rack2'
	}, {
		id: startID+43,
		tag: 'rack3'
	}, {
		id: startID+44,
		tag: 'tableKitchen'
	}, {
		id: startID+45,
		tag: 'doorKitchen'
	}, {
		id: startID+46,
		tag: 'doorRestaurant'
	}
	];
};

exports.getRooms = function(startID) {
	return [{
		id: startID,
		tag: 'floorRoomsPart1'
	}, {
		id: startID+1,
		tag: 'floorRoomsPart2'
	}, {
		id: startID+2,
		tag: 'floorRoomsPart3'
	}, {
		id: startID+3,
		tag: 'floorRoomsPart4'
	}, {
		id: startID+4,
		tag: 'wallRooms1'
	}, {
		id: startID+5,
		tag: 'wallRooms2'
	}, {
		id: startID+6,
		tag: 'wallRooms3'
	}, {
		id: startID+7,
		tag: 'wallRooms4'
	}, {
		id: startID+8,
		tag: 'wallRooms5'
	}, {
		id: startID+9,
		tag: 'wallRooms6'
	}, {
		id: startID+10,
		tag: 'wallRooms7'
	}, {
		id: startID+11,
		tag: 'wallRooms8'
	}, {
		id: startID+12,
		tag: 'wallRooms9'
	}, {
		id: startID+13,
		tag: 'wallRooms10'
	}, {
		id: startID+14,
		tag: 'wallRooms11'
	}, {
		id: startID+15,
		tag: 'wallRooms12'
	}, {
		id: startID+16,
		tag: 'wallRooms13'
	}, {
		id: startID+17,
		tag: 'wallRooms14'
	}, {
		id: startID+18,
		tag: 'wallRooms15'
	}, {
		id: startID+19,
		tag: 'wallRooms16'
	}, {
		id: startID+20,
		tag: 'wallRooms17'
	}, {
		id: startID+21,
		tag: 'wallRooms18'
	}, {
		id: startID+22,
		tag: 'wallRooms19'
	}, {
		id: startID+23,
		tag: 'wallRooms20'
	}, {
		id: startID+24,
		tag: 'wallRooms21'
	}, {
		id: startID+25,
		tag: 'wallRooms22'
	}, {
		id: startID+26,
		tag: 'wallRooms23'
	}, {
		id: startID+27,
		tag: 'wallRooms24'
	}, {
		id: startID+28,
		tag: 'wallRooms25'
	}, {
		id: startID+29,
		tag: 'wallRooms26'
	}, {
		id: startID+30,
		tag: 'wallRooms27'
	}, {
		id: startID+31,
		tag: 'wallRooms28'
	}, {
		id: startID+32,
		tag: 'wallRooms29'
	}, {
		id: startID+33,
		tag: 'wallRooms30'
	}, {
		id: startID+34,
		tag: 'wallRooms31'
	}, {
		id: startID+35,
		tag: 'wallRooms32'
	}, {
		id: startID+36,
		tag: 'wallRooms33'
	}, {
		id: startID+37,
		tag: 'wallRooms34'
	}, {
		id: startID+38,
		tag: 'wallRooms35'
	}, {
		id: startID+39,
		tag: 'wallRooms36'
	}, {
		id: startID+40,
		tag: 'wallRooms37'
	}, {
		id: startID+41,
		tag: 'wallRooms38'
	}, {
		id: startID+42,
		tag: 'wallRooms39'
	}, {
		id: startID+43,
		tag: 'wallRooms40'
	}, {
		id: startID+44,
		tag: 'wallRooms41'
	}, {
		id: startID+45,
		tag: 'wallRooms42'
	}, {
		id: startID+46,
		tag: 'wallRooms43'
	}, {
		id: startID+47,
		tag: 'wallRooms44'
	}, {
		id: startID+48,
		tag: 'wallRooms45'
	}, {
		id: startID+49,
		tag: 'wallRooms46'
	}, {
		id: startID+50,
		tag: 'wallRooms47'
	}, {
		id: startID+51,
		tag: 'wallRooms48'
	}, {
		id: startID+52,
		tag: 'wallRooms49'
	}, {
		id: startID+53,
		tag: 'wallRooms50'
	}, {
		id: startID+54,
		tag: 'wallRooms51'
	}, {
		id: startID+55,
		tag: 'wallRooms52'
	}, {
		id: startID+56,
		tag: 'wallRooms53'
	}, {
		id: startID+57,
		tag: 'wallRooms54'
	}, {
		id: startID+58,
		tag: 'wallRooms55'
	}, {
		id: startID+59,
		tag: 'wallRooms56'
	}, {
		id: startID+60,
		tag: 'wallRooms57'
	}, {
		id: startID+61,
		tag: 'wallRooms58'
	}, {
		id: startID+62,
		tag: 'wallRooms59'
	}, {
		id: startID+63,
		tag: 'wallRooms60'
	}, {
		id: startID+64,
		tag: 'wallRooms61'
	}, {
		id: startID+65,
		tag: 'wallRooms62'
	}, {
		id: startID+67,
		tag: 'wallRooms63'
	}, {
		id: startID+68,
		tag: 'wallRooms64'
	}, {
		id: startID+69,
		tag: 'wallRooms65'
	}, {
		id: startID+70,
		tag: 'door1Rooms'
	}, {
		id: startID+71,
		tag: 'door2Rooms'
	}, {
		id: startID+72,
		tag: 'door3Rooms'
	}, {
		id: startID+73,
		tag: 'door4Rooms'
	}, {
		id: startID+74,
		tag: 'door5Rooms'
	}, {
		id: startID+75,
		tag: 'door6Rooms'
	}, {
		id: startID+76,
		tag: 'door7Rooms'
	}, {
		id: startID+77,
		tag: 'door8Rooms'
	}, {
		id: startID+78,
		tag: 'door9Rooms'
	}, {
		id: startID+79,
		tag: 'door10Rooms'
	}, {
		id: startID+90,
		tag: 'door11Rooms'
	}, {
		id: startID+91,
		tag: 'door12Rooms'
	}, {
		id: startID+92,
		tag: 'bath1Rooms'
	}, {
		id: startID+93,
		tag: 'toilet1Rooms'
	}, {
		id: startID+94,
		tag: 'sink1Rooms'
	}, {
		id: startID+95,
		tag: 'floor1Bath'
	}, {
		id: startID+96,
		tag: 'wall1Bath1'
	}, {
		id: startID+97,
		tag: 'wall1Bath2'
	}, {
		id: startID+98,
		tag: 'wall1Bath3'
	}, {
		id: startID+99,
		tag: 'wall1Bath4'
	}, {
		id: startID+100,
		tag: 'wall1Bath5'
	}, {
		id: startID+101,
		tag: 'wall1Bath6'
	}, {
		id: startID+102,
		tag: 'wall1Bath7'
	}, {
		id: startID+103,
		tag: 'door1Bath'
	}, {
		id: startID+104,
		tag: 'cupboard1'
	}, {
		id: startID+105,
		tag: 'bedsideTable1Room1'
	}, {
		id: startID+106,
		tag: 'bed1'
	}, {
		id: startID+107,
		tag: 'bedsideTable1Room2'
	}, {
		id: startID+108,
		tag: 'tv1'
	}, {
		id: startID+109,
		tag: 'bath2Rooms'
	}, {
		id: startID+110,
		tag: 'toilet2Rooms'
	}, {
		id: startID+111,
		tag: 'sink2Rooms'
	}, {
		id: startID+112,
		tag: 'floor2Bath'
	}, {
		id: startID+113,
		tag: 'wall2Bath1'
	}, {
		id: startID+114,
		tag: 'wall2Bath2'
	}, {
		id: startID+115,
		tag: 'wall2Bath3'
	}, {
		id: startID+116,
		tag: 'wall2Bath4'
	}, {
		id: startID+117,
		tag: 'wall2Bath5'
	}, {
		id: startID+118,
		tag: 'wall2Bath6'
	}, {
		id: startID+119,
		tag: 'wall2Bath7'
	}, {
		id: startID+120,
		tag: 'door2Bath'
	}, {
		id: startID+121,
		tag: 'cupboard2'
	}, {
		id: startID+122,
		tag: 'bedsideTable2Room1'
	}, {
		id: startID+123,
		tag: 'bed2'
	}, {
		id: startID+124,
		tag: 'bedsideTable2Room2'
	}, {
		id: startID+125,
		tag: 'tv2'
	}, {
		id: startID+126,
		tag: 'bath3Rooms'
	}, {
		id: startID+127,
		tag: 'toilet3Rooms'
	}, {
		id: startID+128,
		tag: 'sink3Rooms'
	}, {
		id: startID+129,
		tag: 'floor3Bath'
	}, {
		id: startID+130,
		tag: 'wall3Bath1'
	}, {
		id: startID+131,
		tag: 'wall3Bath2'
	}, {
		id: startID+132,
		tag: 'wall3Bath3'
	}, {
		id: startID+133,
		tag: 'wall3Bath4'
	}, {
		id: startID+134,
		tag: 'wall3Bath5'
	}, {
		id: startID+135,
		tag: 'wall3Bath6'
	}, {
		id: startID+136,
		tag: 'wall3Bath7'
	}, {
		id: startID+137,
		tag: 'door3Bath'
	}, {
		id: startID+138,
		tag: 'cupboard3'
	}, {
		id: startID+139,
		tag: 'bedsideTable3Room1'
	}, {
		id: startID+140,
		tag: 'bed3'
	}, {
		id: startID+141,
		tag: 'bedsideTable3Room2'
	}, {
		id: startID+142,
		tag: 'tv3'
	}, {
		id: startID+143,
		tag: 'bath4Rooms'
	}, {
		id: startID+144,
		tag: 'toilet4Rooms'
	}, {
		id: startID+145,
		tag: 'sink4Rooms'
	}, {
		id: startID+146,
		tag: 'floor4Bath'
	}, {
		id: startID+147,
		tag: 'wall4Bath1'
	}, {
		id: startID+148,
		tag: 'wall4Bath2'
	}, {
		id: startID+149,
		tag: 'wall4Bath3'
	}, {
		id: startID+150,
		tag: 'wall4Bath4'
	}, {
		id: startID+151,
		tag: 'wall4Bath5'
	}, {
		id: startID+152,
		tag: 'wall4Bath6'
	}, {
		id: startID+153,
		tag: 'wall4Bath7'
	}, {
		id: startID+154,
		tag: 'door4Bath'
	}, {
		id: startID+155,
		tag: 'cupboard4'
	}, {
		id: startID+156,
		tag: 'bedsideTable4Room1'
	}, {
		id: startID+157,
		tag: 'bed4'
	}, {
		id: startID+158,
		tag: 'bedsideTable4Room2'
	}, {
		id: startID+159,
		tag: 'tv4'
	}, {
		id: startID+160,
		tag: 'bath5Rooms'
	}, {
		id: startID+161,
		tag: 'toilet5Rooms'
	}, {
		id: startID+162,
		tag: 'sink5Rooms'
	}, {
		id: startID+163,
		tag: 'floor5Bath'
	}, {
		id: startID+164,
		tag: 'wall5Bath1'
	}, {
		id: startID+165,
		tag: 'wall5Bath2'
	}, {
		id: startID+166,
		tag: 'wall5Bath3'
	}, {
		id: startID+167,
		tag: 'wall5Bath4'
	}, {
		id: startID+168,
		tag: 'wall5Bath5'
	}, {
		id: startID+169,
		tag: 'wall5Bath6'
	}, {
		id: startID+170,
		tag: 'wall5Bath7'
	}, {
		id: startID+171,
		tag: 'door5Bath'
	}, {
		id: startID+172,
		tag: 'cupboard5'
	}, {
		id: startID+173,
		tag: 'bedsideTable5Room1'
	}, {
		id: startID+174,
		tag: 'bed5'
	}, {
		id: startID+175,
		tag: 'bedsideTable5Room2'
	}, {
		id: startID+176,
		tag: 'tv5'
	}, {
		id: startID+177,
		tag: 'bath6Rooms'
	}, {
		id: startID+178,
		tag: 'toilet6Rooms'
	}, {
		id: startID+179,
		tag: 'sink6Rooms'
	}, {
		id: startID+180,
		tag: 'floor6Bath'
	}, {
		id: startID+181,
		tag: 'wall6Bath1'
	}, {
		id: startID+182,
		tag: 'wall6Bath2'
	}, {
		id: startID+183,
		tag: 'wall6Bath3'
	}, {
		id: startID+184,
		tag: 'wall6Bath4'
	}, {
		id: startID+185,
		tag: 'wall6Bath5'
	}, {
		id: startID+186,
		tag: 'wall6Bath6'
	}, {
		id: startID+187,
		tag: 'wall6Bath7'
	}, {
		id: startID+188,
		tag: 'door6Bath'
	}, {
		id: startID+189,
		tag: 'cupboard6'
	}, {
		id: startID+190,
		tag: 'bedsideTable6Room1'
	}, {
		id: startID+191,
		tag: 'bed6'
	}, {
		id: startID+192,
		tag: 'bedsideTable6Room2'
	}, {
		id: startID+193,
		tag: 'tv6'
	}, {
		id: startID+194,
		tag: 'bath7Rooms'
	}, {
		id: startID+195,
		tag: 'toilet7Rooms'
	}, {
		id: startID+196,
		tag: 'sink7Rooms'
	}, {
		id: startID+197,
		tag: 'floor7Bath'
	}, {
		id: startID+198,
		tag: 'wall7Bath1'
	}, {
		id: startID+199,
		tag: 'wall7Bath2'
	}, {
		id: startID+200,
		tag: 'wall7Bath3'
	}, {
		id: startID+201,
		tag: 'wall7Bath4'
	}, {
		id: startID+202,
		tag: 'wall7Bath5'
	}, {
		id: startID+203,
		tag: 'wall7Bath6'
	}, {
		id: startID+204,
		tag: 'wall7Bath7'
	}, {
		id: startID+205,
		tag: 'door7Bath'
	}, {
		id: startID+206,
		tag: 'cupboard7'
	}, {
		id: startID+207,
		tag: 'bedsideTable7Room1'
	}, {
		id: startID+208,
		tag: 'bed7'
	}, {
		id: startID+209,
		tag: 'bedsideTable7Room2'
	}, {
		id: startID+210,
		tag: 'tv7'
	}, {
		id: startID+211,
		tag: 'bath8Rooms'
	}, {
		id: startID+212,
		tag: 'toilet8Rooms'
	}, {
		id: startID+213,
		tag: 'sink8Rooms'
	}, {
		id: startID+214,
		tag: 'floor8Bath'
	}, {
		id: startID+215,
		tag: 'wall8Bath1'
	}, {
		id: startID+216,
		tag: 'wall8Bath2'
	}, {
		id: startID+217,
		tag: 'wall8Bath3'
	}, {
		id: startID+218,
		tag: 'wall8Bath4'
	}, {
		id: startID+219,
		tag: 'wall8Bath5'
	}, {
		id: startID+220,
		tag: 'wall8Bath6'
	}, {
		id: startID+221,
		tag: 'wall8Bath7'
	}, {
		id: startID+222,
		tag: 'door8Bath'
	}, {
		id: startID+223,
		tag: 'cupboard8'
	}, {
		id: startID+224,
		tag: 'bedsideTable8Room1'
	}, {
		id: startID+225,
		tag: 'bed8'
	}, {
		id: startID+226,
		tag: 'bedsideTable8Room2'
	}, {
		id: startID+227,
		tag: 'tv8'
	}, {
		id: startID+228,
		tag: 'bath9Rooms'
	}, {
		id: startID+229,
		tag: 'toilet9Rooms'
	}, {
		id: startID+230,
		tag: 'sink9Rooms'
	}, {
		id: startID+231,
		tag: 'floor9Bath'
	}, {
		id: startID+232,
		tag: 'wall9Bath1'
	}, {
		id: startID+233,
		tag: 'wall9Bath2'
	}, {
		id: startID+234,
		tag: 'wall9Bath3'
	}, {
		id: startID+235,
		tag: 'wall9Bath4'
	}, {
		id: startID+236,
		tag: 'wall9Bath5'
	}, {
		id: startID+237,
		tag: 'wall9Bath6'
	}, {
		id: startID+238,
		tag: 'wall9Bath7'
	}, {
		id: startID+239,
		tag: 'door9Bath'
	}, {
		id: startID+240,
		tag: 'cupboard9'
	}, {
		id: startID+241,
		tag: 'bedsideTable9Room1'
	}, {
		id: startID+242,
		tag: 'bed9'
	}, {
		id: startID+243,
		tag: 'bedsideTable9Room2'
	}, {
		id: startID+244,
		tag: 'tv9'
	}, {
		id: startID+244,
		tag: 'bath10Rooms'
	}, {
		id: startID+245,
		tag: 'toilet10Rooms'
	}, {
		id: startID+246,
		tag: 'sink10Rooms'
	}, {
		id: startID+247,
		tag: 'floor10Bath'
	}, {
		id: startID+248,
		tag: 'wall10Bath1'
	}, {
		id: startID+249,
		tag: 'wall10Bath2'
	}, {
		id: startID+250,
		tag: 'wall10Bath3'
	}, {
		id: startID+251,
		tag: 'wall10Bath4'
	}, {
		id: startID+252,
		tag: 'wall10Bath5'
	}, {
		id: startID+253,
		tag: 'wall10Bath6'
	}, {
		id: startID+254,
		tag: 'wall10Bath7'
	}, {
		id: startID+255,
		tag: 'door10Bath'
	}, {
		id: startID+256,
		tag: 'cupboard10'
	}, {
		id: startID+257,
		tag: 'bedsideTable10Room1'
	}, {
		id: startID+258,
		tag: 'bed10'
	}, {
		id: startID+259,
		tag: 'bedsideTable10Room2'
	}, {
		id: startID+260,
		tag: 'tv10'
	}, {
		id: startID+261,
		tag: 'bath11Rooms'
	}, {
		id: startID+262,
		tag: 'toilet11Rooms'
	}, {
		id: startID+263,
		tag: 'sink11Rooms'
	}, {
		id: startID+264,
		tag: 'floor11Bath'
	}, {
		id: startID+265,
		tag: 'wall11Bath1'
	}, {
		id: startID+266,
		tag: 'wall11Bath2'
	}, {
		id: startID+267,
		tag: 'wall11Bath3'
	}, {
		id: startID+268,
		tag: 'wall11Bath4'
	}, {
		id: startID+269,
		tag: 'wall11Bath5'
	}, {
		id: startID+270,
		tag: 'wall11Bath6'
	}, {
		id: startID+271,
		tag: 'wall11Bath7'
	}, {
		id: startID+272,
		tag: 'door11Bath'
	}, {
		id: startID+273,
		tag: 'cupboard11'
	}, {
		id: startID+274,
		tag: 'bedsideTable11Room1'
	}, {
		id: startID+275,
		tag: 'bed11'
	}, {
		id: startID+276,
		tag: 'bedsideTable11Room2'
	}, {
		id: startID+277,
		tag: 'tv11'
	}, {
		id: startID+278,
		tag: 'bath12Rooms'
	}, {
		id: startID+279,
		tag: 'toilet12Rooms'
	}, {
		id: startID+280,
		tag: 'sink12Rooms'
	}, {
		id: startID+281,
		tag: 'floor12Bath'
	}, {
		id: startID+282,
		tag: 'wall12Bath1'
	}, {
		id: startID+283,
		tag: 'wall12Bath2'
	}, {
		id: startID+284,
		tag: 'wall12Bath3'
	}, {
		id: startID+285,
		tag: 'wall12Bath4'
	}, {
		id: startID+286,
		tag: 'wall12Bath5'
	}, {
		id: startID+287,
		tag: 'wall12Bath6'
	}, {
		id: startID+288,
		tag: 'wall12Bath7'
	}, {
		id: startID+289,
		tag: 'door12Bath'
	}, {
		id: startID+290,
		tag: 'cupboard12'
	}, {
		id: startID+291,
		tag: 'bedsideTable12Room1'
	}, {
		id: startID+292,
		tag: 'bed12'
	}, {
		id: startID+293,
		tag: 'bedsideTable12Room2'
	}, {
		id: startID+294,
		tag: 'tv12'
	}, {
		id: startID+295,
		tag: 'door13Rooms'
	}, {
		id: startID+296,
		tag: 'wall13Bath1'
	}, {
		id: startID+297,
		tag: 'wall13Bath2'
	}, {
		id: startID+298,
		tag: 'wall13Bath3'
	}, {
		id: startID+299,
		tag: 'wall13Bath4'
	}, {
		id: startID+300,
		tag: 'wall13Bath5'
	}, {
		id: startID+301,
		tag: 'door13Rooms2'
	}, {
		id: startID+302,
		tag: 'door13Rooms3'
	}, {
		id: startID+303,
		tag: 'wall13Bath6'
	}, {
		id: startID+304,
		tag: 'wall13Bath7'
	}, {
		id: startID+305,
		tag: 'wall13Bath8'
	}, {
		id: startID+306,
		tag: 'wall13Bath9'
	}, {
		id: startID+307,
		tag: 'wall13Bath10'
	}, {
		id: startID+308,
		tag: 'wall13Bath11'
	}, {
		id: startID+309,
		tag: 'floor13Bath1'
	}, {
		id: startID+310,
		tag: 'floor13Bath2'
	}, {
		id: startID+311,
		tag: 'toilet13Rooms'
	}, {
		id: startID+312,
		tag: 'bath13Rooms'
	}, {
		id: startID+313,
		tag: 'sink13Rooms'
	}, {
		id: startID+314,
		tag: 'cupboard13'
	}, {
		id: startID+315,
		tag: 'bedsideTable13Room1'
	}, {
		id: startID+316,
		tag: 'bed13'
	}, {
		id: startID+317,
		tag: 'bedsideTable13Room2'
	}, {
		id: startID+318,
		tag: 'tv13'
	}, {
		id: startID+319,
		tag: 'wall14Bath1'
	}, {
		id: startID+320,
		tag: 'wall14Bath2'
	}, {
		id: startID+321,
		tag: 'wall14Bath3'
	}, {
		id: startID+322,
		tag: 'wall14Bath4'
	}, {
		id: startID+323,
		tag: 'door14Bath1'
	}, {
		id: startID+324,
		tag: 'door14Bath2'
	}, {
		id: startID+325,
		tag: 'wall14Bath5'
	}, {
		id: startID+326,
		tag: 'wall14Bath6'
	}, {
		id: startID+327,
		tag: 'wall14Bath7'
	}, {
		id: startID+328,
		tag: 'wall14Bath8'
	}, {
		id: startID+329,
		tag: 'wall14Bath9'
	}, {
		id: startID+330,
		tag: 'floor14Bath'
	}, {
		id: startID+331,
		tag: 'toilet14Rooms'
	}, {
		id: startID+332,
		tag: 'bath14Rooms1'
	}, {
		id: startID+333,
		tag: 'sink14Rooms'
	}, {
		id: startID+334,
		tag: 'shower14Rooms'
	}, {
		id: startID+335,
		tag: 'wall14Bath10'
	}, {
		id: startID+336,
		tag: 'wall14Bath11'
	}, {
		id: startID+337,
		tag: 'wall14Bath12'
	}, {
		id: startID+338,
		tag: 'door14Bath3'
	}, {
		id: startID+339,
		tag: 'bedsideTable14Room1'
	}, {
		id: startID+340,
		tag: 'bed14'
	}, {
		id: startID+341,
		tag: 'bedsideTable14Room2'
	}, {
		id: startID+342,
		tag: 'cupboard14'
	}, {
		id: startID+343,
		tag: 'sofa14'
	}, {
		id: startID+344,
		tag: 'tv14'
	}, {
		id: startID+345,
		tag: 'poolTable14'
	}, {
		id: startID+346,
		tag: 'door14Bath4'
	}, {
		id: startID+347,
		tag: 'door14Rooms'
	}, {
		id: startID+348,
		tag: 'window1Rooms'
	}, {
		id: startID+349,
		tag: 'window2Rooms'
	}, {
		id: startID+350,
		tag: 'window3Rooms'
	}, {
		id: startID+351,
		tag: 'window4Rooms'
	}, {
		id: startID+352,
		tag: 'window14Rooms1'
	}, {
		id: startID+353,
		tag: 'window14Rooms2'
	}
	];
};

exports.getSecurity = function(startID) {
	return [{
		id: startID,
		tag: 'floorSecurity'
	}, {
		id: startID+1,
		tag: 'wallSecurity1'
	}, {
		id: startID+2,
		tag: 'wallSecurity2'
	}, {
		id: startID+3,
		tag: 'wallSecurity3'
	}, {
		id: startID+4,
		tag: 'wallSecurity4'
	}, {
		id: startID+5,
		tag: 'wallSecurity5'
	}, {
		id: startID+6,
		tag: 'cctvSecurity'
	}, {
		id: startID+7,
		tag: 'doorSecurity'
	}, {
		id: startID+8,
		tag: 'cupboardSecurity1'
	}, {
		id: startID+9,
		tag: 'cupboardSecurity2'
	}, {
		id: startID+10,
		tag: 'chairSecurity'
	}
	];
};
